runtime: php82
service: lisztium-mailer # Or your chosen service name
entrypoint: serve send.php

env_variables:
  SMTP_HOST: "smtp.gmail.com" # Change if using SendGrid, etc.
  SMTP_USER: "musicorestes@gmail.com"
  SMTP_PASS: "asdlxbmhlkenvqgt"
  ADMIN_EMAIL: "musicorestes@gmail.com"
  FROM_EMAIL: "musicorestes@gmail.com" # Or a dedicated no-reply@yourdomain.com
  FROM_NAME: "Lisztium Application"

handlers:
  - url: /.* # Route all requests to send.php
    script: send.php
