runtime: php82
service: lisztium-mailer # Or your chosen service name
entrypoint: serve send.php

env_variables:
  SMTP_HOST: "smtp.gmail.com" # Change if using SendGrid, etc.
  SMTP_USER: "your_gmail_username_or_sendgrid_apikey" # For Gmail, your email; for SendGrid, usually 'apikey'
  SMTP_PASS: "your_gmail_app_password_or_sendgrid_api_key_value"
  ADMIN_EMAIL: "szabolcs.szelenyi@net4yard.com"
  FROM_EMAIL: "szabolcs.szelenyi@net4yard.com" # Or a dedicated no-reply@yourdomain.com
  FROM_NAME: "Lisztium Application"

handlers:
  - url: /.* # Route all requests to send.php
    script: send.php
# If you had a thankyou.html in the root you wanted to serve directly:
# - url: /thankyou.html
#   static_files: thankyou.html
#   upload: thankyou.html
